### ISSUE TITLE
String is not an file url

### ISSUE THREAD

**Issue by ZiomaleQ** [SkyStar-modules/Stowrage#6]
I think that URL is missing `file://` at the start of the string, and that's why it isn't interpreted as an URL instead of the file URL

```
error: Uncaught TypeError: Must be a file URL.
        throw new TypeError("Must be a file URL.");
              ^
    at pathFromURL (deno:runtime/js/06_util.js:92:15)
    at Object.statSync (deno:runtime/js/30_fs.js:233:13)
    at pathExistSync (<https://deno.land/x/stowrage@v0.3.1/src/filesystem.ts>:3:1)      
    at new Stowrage (<https://deno.land/x/stowrage@v0.3.1/src/stowrage.ts>:63:1)        
    at <file:///D:/Typescript/baibai-api/src/db.ts>:7:1
    ```

**Comment by MierenManz** [comment]
do you have some code that can reproduce this bug?

**Comment by ZiomaleQ** [comment]
Copy the content below into the new file and run it it will show a similar message to the one shown above
```ts
import {Stowrage} from "https://deno.land/x/stowrage@v0.3.1/mod.ts"

new Stowrage<string>()
```

**Comment by MierenManz** [comment]
I'll run these tests on my pc later, then I know for sure if it works
